#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Translyte.Android.Resource", IsApplication=true)]

namespace Translyte.Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::ResideMenu.Resource.Drawable.shadow = global::Translyte.Android.Resource.Drawable.shadow;
			global::ResideMenu.Resource.Id.iv_background = global::Translyte.Android.Resource.Id.iv_background;
			global::ResideMenu.Resource.Id.iv_icon = global::Translyte.Android.Resource.Id.iv_icon;
			global::ResideMenu.Resource.Id.iv_shadow = global::Translyte.Android.Resource.Id.iv_shadow;
			global::ResideMenu.Resource.Id.layout_left_menu = global::Translyte.Android.Resource.Id.layout_left_menu;
			global::ResideMenu.Resource.Id.layout_right_menu = global::Translyte.Android.Resource.Id.layout_right_menu;
			global::ResideMenu.Resource.Id.sv_left_menu = global::Translyte.Android.Resource.Id.sv_left_menu;
			global::ResideMenu.Resource.Id.sv_right_menu = global::Translyte.Android.Resource.Id.sv_right_menu;
			global::ResideMenu.Resource.Id.tv_title = global::Translyte.Android.Resource.Id.tv_title;
			global::ResideMenu.Resource.Layout.residemenu = global::Translyte.Android.Resource.Layout.residemenu;
			global::ResideMenu.Resource.Layout.residemenu_item = global::Translyte.Android.Resource.Layout.residemenu_item;
			global::ResideMenu.Resource.String.app_name = global::Translyte.Android.Resource.String.app_name;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int AppIcon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int book1 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int book2 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Bookmarks = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int button = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int button_on = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int button_selector = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int dark = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int frame = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int game = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int gesture = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int Icon = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int icon_home = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int icon_profile = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int icon_settings = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int Library = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int lotr = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int menu_background = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int optionsmenu = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int shadow = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int splash = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int splash2 = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int title_bar_menu = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int title_bar_menu_on = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int titlebar_menu_selector = 2130837528;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060007
			public const int Author = 2131099655;
			
			// aapt resource value: 0x7f060012
			public const int AuthorCurrent = 2131099666;
			
			// aapt resource value: 0x7f060005
			public const int Cover = 2131099653;
			
			// aapt resource value: 0x7f060010
			public const int CoverCurrent = 2131099664;
			
			// aapt resource value: 0x7f060016
			public const int IsAvailable = 2131099670;
			
			// aapt resource value: 0x7f060015
			public const int ListView = 2131099669;
			
			// aapt resource value: 0x7f060013
			public const int ProgressCurrent = 2131099667;
			
			// aapt resource value: 0x7f060017
			public const int ScrollView = 2131099671;
			
			// aapt resource value: 0x7f060014
			public const int TimeCurrent = 2131099668;
			
			// aapt resource value: 0x7f060006
			public const int Title = 2131099654;
			
			// aapt resource value: 0x7f060011
			public const int TitleCurrent = 2131099665;
			
			// aapt resource value: 0x7f06001f
			public const int addnew = 2131099679;
			
			// aapt resource value: 0x7f060018
			public const int iv_background = 2131099672;
			
			// aapt resource value: 0x7f06001e
			public const int iv_icon = 2131099678;
			
			// aapt resource value: 0x7f060019
			public const int iv_shadow = 2131099673;
			
			// aapt resource value: 0x7f06001b
			public const int layout_left_menu = 2131099675;
			
			// aapt resource value: 0x7f06001d
			public const int layout_right_menu = 2131099677;
			
			// aapt resource value: 0x7f06000d
			public const int layout_top = 2131099661;
			
			// aapt resource value: 0x7f060009
			public const int ll_bookContent = 2131099657;
			
			// aapt resource value: 0x7f060001
			public const int loginText = 2131099649;
			
			// aapt resource value: 0x7f06000c
			public const int main_fragment = 2131099660;
			
			// aapt resource value: 0x7f060003
			public const int passwordText = 2131099651;
			
			// aapt resource value: 0x7f060021
			public const int refresher = 2131099681;
			
			// aapt resource value: 0x7f060020
			public const int searcher = 2131099680;
			
			// aapt resource value: 0x7f060004
			public const int signUpButton = 2131099652;
			
			// aapt resource value: 0x7f060008
			public const int sv_bookContent = 2131099656;
			
			// aapt resource value: 0x7f06001a
			public const int sv_left_menu = 2131099674;
			
			// aapt resource value: 0x7f06001c
			public const int sv_right_menu = 2131099676;
			
			// aapt resource value: 0x7f060002
			public const int textView2 = 2131099650;
			
			// aapt resource value: 0x7f060000
			public const int textView3 = 2131099648;
			
			// aapt resource value: 0x7f06000e
			public const int title_bar_left_menu = 2131099662;
			
			// aapt resource value: 0x7f06000f
			public const int title_bar_right_menu = 2131099663;
			
			// aapt resource value: 0x7f06000b
			public const int tv_book = 2131099659;
			
			// aapt resource value: 0x7f06000a
			public const int tv_title = 2131099658;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AuthenticationView = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int BookItemView = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int BookView = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int LibraryView = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int ParseLibraryBookItemView = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int ParseLibraryView = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int residemenu = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int residemenu_item = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int SettingsView = 2130903048;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040002
			public const int ApplicationName = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int Hello = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int Theme_Splash = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
