#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Translyte.Android.Resource", IsApplication=true)]

namespace Translyte.Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::ResideMenu.Resource.Drawable.shadow = global::Translyte.Android.Resource.Drawable.shadow;
			global::ResideMenu.Resource.Id.iv_background = global::Translyte.Android.Resource.Id.iv_background;
			global::ResideMenu.Resource.Id.iv_icon = global::Translyte.Android.Resource.Id.iv_icon;
			global::ResideMenu.Resource.Id.iv_shadow = global::Translyte.Android.Resource.Id.iv_shadow;
			global::ResideMenu.Resource.Id.layout_left_menu = global::Translyte.Android.Resource.Id.layout_left_menu;
			global::ResideMenu.Resource.Id.layout_right_menu = global::Translyte.Android.Resource.Id.layout_right_menu;
			global::ResideMenu.Resource.Id.sv_left_menu = global::Translyte.Android.Resource.Id.sv_left_menu;
			global::ResideMenu.Resource.Id.sv_right_menu = global::Translyte.Android.Resource.Id.sv_right_menu;
			global::ResideMenu.Resource.Id.tv_title = global::Translyte.Android.Resource.Id.tv_title;
			global::ResideMenu.Resource.Layout.residemenu = global::Translyte.Android.Resource.Layout.residemenu;
			global::ResideMenu.Resource.Layout.residemenu_item = global::Translyte.Android.Resource.Layout.residemenu_item;
			global::ResideMenu.Resource.String.app_name = global::Translyte.Android.Resource.String.app_name;
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f050001
			public const int font_array = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int size_array = 2131034112;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int AppIcon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int book1 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int book2 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Bookmarks = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Bookmarks_black = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int button = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int button_on = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int button_selector = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int dark = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int file = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int fileSave = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int folder = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int frame = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int game = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int gesture = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int Icon = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int icon_home = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int icon_profile = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int icon_settings = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int Library = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int lotr = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int menu_background = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int Note = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int optionsmenu = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int shadow = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int splash = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int splash2 = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int title_bar_menu = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int title_bar_menu_on = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int titlebar_menu_selector = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int translate = 2130837534;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070007
			public const int Author = 2131165191;
			
			// aapt resource value: 0x7f070017
			public const int AuthorCurrent = 2131165207;
			
			// aapt resource value: 0x7f070005
			public const int Cover = 2131165189;
			
			// aapt resource value: 0x7f070015
			public const int CoverCurrent = 2131165205;
			
			// aapt resource value: 0x7f07000d
			public const int FilesListView = 2131165197;
			
			// aapt resource value: 0x7f07001b
			public const int IsAvailable = 2131165211;
			
			// aapt resource value: 0x7f070018
			public const int ListView = 2131165208;
			
			// aapt resource value: 0x7f070010
			public const int ScrollView = 2131165200;
			
			// aapt resource value: 0x7f070006
			public const int Title = 2131165190;
			
			// aapt resource value: 0x7f070016
			public const int TitleCurrent = 2131165206;
			
			// aapt resource value: 0x7f07002e
			public const int add_bookmark = 2131165230;
			
			// aapt resource value: 0x7f07002f
			public const int add_note = 2131165231;
			
			// aapt resource value: 0x7f070024
			public const int appThemeSwitch = 2131165220;
			
			// aapt resource value: 0x7f070008
			public const int bookLayout = 2131165192;
			
			// aapt resource value: 0x7f07002b
			public const int edit_name = 2131165227;
			
			// aapt resource value: 0x7f07000e
			public const int file_picker_image = 2131165198;
			
			// aapt resource value: 0x7f07000f
			public const int file_picker_text = 2131165199;
			
			// aapt resource value: 0x7f07001c
			public const int iv_background = 2131165212;
			
			// aapt resource value: 0x7f070022
			public const int iv_icon = 2131165218;
			
			// aapt resource value: 0x7f07001d
			public const int iv_shadow = 2131165213;
			
			// aapt resource value: 0x7f070014
			public const int last_book_view = 2131165204;
			
			// aapt resource value: 0x7f070025
			public const int layout1 = 2131165221;
			
			// aapt resource value: 0x7f070028
			public const int layout11 = 2131165224;
			
			// aapt resource value: 0x7f07001f
			public const int layout_left_menu = 2131165215;
			
			// aapt resource value: 0x7f070021
			public const int layout_right_menu = 2131165217;
			
			// aapt resource value: 0x7f070011
			public const int layout_top = 2131165201;
			
			// aapt resource value: 0x7f07000a
			public const int ll_bookContent = 2131165194;
			
			// aapt resource value: 0x7f070001
			public const int loginText = 2131165185;
			
			// aapt resource value: 0x7f070019
			public const int main_fragment = 2131165209;
			
			// aapt resource value: 0x7f070003
			public const int passwordText = 2131165187;
			
			// aapt resource value: 0x7f07001a
			public const int popup_fragment = 2131165210;
			
			// aapt resource value: 0x7f070004
			public const int signUpButton = 2131165188;
			
			// aapt resource value: 0x7f070009
			public const int sv_bookContent = 2131165193;
			
			// aapt resource value: 0x7f07001e
			public const int sv_left_menu = 2131165214;
			
			// aapt resource value: 0x7f070020
			public const int sv_right_menu = 2131165216;
			
			// aapt resource value: 0x7f07002a
			public const int testtw = 2131165226;
			
			// aapt resource value: 0x7f070029
			public const int textFont = 2131165225;
			
			// aapt resource value: 0x7f070027
			public const int textSize = 2131165223;
			
			// aapt resource value: 0x7f070026
			public const int textView1 = 2131165222;
			
			// aapt resource value: 0x7f070002
			public const int textView2 = 2131165186;
			
			// aapt resource value: 0x7f070000
			public const int textView3 = 2131165184;
			
			// aapt resource value: 0x7f070023
			public const int themeSwitch = 2131165219;
			
			// aapt resource value: 0x7f070012
			public const int title_bar_left_menu = 2131165202;
			
			// aapt resource value: 0x7f070013
			public const int title_bar_right_menu = 2131165203;
			
			// aapt resource value: 0x7f07002c
			public const int tranlation = 2131165228;
			
			// aapt resource value: 0x7f07002d
			public const int translate = 2131165229;
			
			// aapt resource value: 0x7f07000c
			public const int tv_book = 2131165196;
			
			// aapt resource value: 0x7f07000b
			public const int tv_title = 2131165195;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AuthenticationView = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int BookItemView = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int BookView = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int FileExplorerView = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int FileListItemView = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int LibraryBookItemView = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int LibraryView = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int ParseLibraryBookItemView = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int ParseLibraryView = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int residemenu = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int residemenu_item = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int SettingsView = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int Spinner = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int TranslateMessage = 2130903053;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040002
			public const int ApplicationName = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int Hello = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			// aapt resource value: 0x7f040004
			public const int textFonts = 2130968580;
			
			// aapt resource value: 0x7f040003
			public const int textSizes = 2130968579;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int Theme_Splash = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
