#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("WordSelection.Resource", IsApplication=true)]

namespace WordSelection
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::ResideMenu.Resource.Drawable.shadow = global::WordSelection.Resource.Drawable.shadow;
			global::ResideMenu.Resource.Id.iv_background = global::WordSelection.Resource.Id.iv_background;
			global::ResideMenu.Resource.Id.iv_icon = global::WordSelection.Resource.Id.iv_icon;
			global::ResideMenu.Resource.Id.iv_shadow = global::WordSelection.Resource.Id.iv_shadow;
			global::ResideMenu.Resource.Id.layout_left_menu = global::WordSelection.Resource.Id.layout_left_menu;
			global::ResideMenu.Resource.Id.layout_right_menu = global::WordSelection.Resource.Id.layout_right_menu;
			global::ResideMenu.Resource.Id.sv_left_menu = global::WordSelection.Resource.Id.sv_left_menu;
			global::ResideMenu.Resource.Id.sv_right_menu = global::WordSelection.Resource.Id.sv_right_menu;
			global::ResideMenu.Resource.Id.tv_title = global::WordSelection.Resource.Id.tv_title;
			global::ResideMenu.Resource.Layout.residemenu = global::WordSelection.Resource.Layout.residemenu;
			global::ResideMenu.Resource.Layout.residemenu_item = global::WordSelection.Resource.Layout.residemenu_item;
			global::ResideMenu.Resource.String.app_name = global::WordSelection.Resource.String.app_name;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int book1 = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int book2 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int book3 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int book4 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Bookmarks = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int button = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int button_on = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int button_selector = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int frame = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int gesture = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int Icon = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int icon_home = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int icon_profile = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int icon_settings = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int Library = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int menu_background = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int optionsmenu = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int shadow = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int title_bar_menu = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int title_bar_menu_on = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int titlebar_menu_selector = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int Untitled = 2130837525;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050003
			public const int Author = 2131034115;
			
			// aapt resource value: 0x7f050001
			public const int Cover = 2131034113;
			
			// aapt resource value: 0x7f050004
			public const int IsAvailable = 2131034116;
			
			// aapt resource value: 0x7f050000
			public const int ScrollView = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int Title = 2131034114;
			
			// aapt resource value: 0x7f050012
			public const int addnew = 2131034130;
			
			// aapt resource value: 0x7f05000a
			public const int iv_background = 2131034122;
			
			// aapt resource value: 0x7f050010
			public const int iv_icon = 2131034128;
			
			// aapt resource value: 0x7f05000b
			public const int iv_shadow = 2131034123;
			
			// aapt resource value: 0x7f05000d
			public const int layout_left_menu = 2131034125;
			
			// aapt resource value: 0x7f05000f
			public const int layout_right_menu = 2131034127;
			
			// aapt resource value: 0x7f050006
			public const int layout_top = 2131034118;
			
			// aapt resource value: 0x7f050009
			public const int main_fragment = 2131034121;
			
			// aapt resource value: 0x7f050014
			public const int refresher = 2131034132;
			
			// aapt resource value: 0x7f050005
			public const int rmt = 2131034117;
			
			// aapt resource value: 0x7f050013
			public const int searcher = 2131034131;
			
			// aapt resource value: 0x7f05000c
			public const int sv_left_menu = 2131034124;
			
			// aapt resource value: 0x7f05000e
			public const int sv_right_menu = 2131034126;
			
			// aapt resource value: 0x7f050007
			public const int title_bar_left_menu = 2131034119;
			
			// aapt resource value: 0x7f050008
			public const int title_bar_right_menu = 2131034120;
			
			// aapt resource value: 0x7f050011
			public const int tv_title = 2131034129;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int BookItemView = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Home = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int residemenu = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int residemenu_item = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040002
			public const int ApplicationName = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int Hello = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
